### ISSUE TITLE
Any medium page keeps reloading forever

### ISSUE THREAD

**Issue by diesazul96** [manojVivek/medium-unlimited#118]
The extension seems to not be working anymore... when i go inside any medium page the website starts to reload like trying to activate the unlimited medium but never works, it reloads forever.

**Comment by manojVivek** [comment]
@diesazul96 Can you let us know the version of the extension you are using?

We have fixed this issue on the latest version(v1.7.0), please update it if you don't have it.

**Comment by danylkaaa** [comment]
Still not working with v1.7.0. Think, this can be related to #116 

![](https://user-images.githubusercontent.com/17959494/111910648-ed758300-8a6a-11eb-8425-dbe5b2293506.png)

**Comment by Jurabek** [comment]
@danylkaaa @diesazul96 I had the same problem, however, mine is working after login in to the medium account.

**Comment by nipnipj** [comment]
Hello!
I'm using version 1.7.0, but I cannot acces to https://towardsdatascience.com/the-first-step-in-bayesian-time-series-linear-regression-89a64b826a7e

**Comment by deadcoder0904** [comment]
Same, it's not working anymore on v1.4.13

**Comment by deadcoder0904** [comment]
It works with the latest v1.7.0 👍

**Comment by nipnipj** [comment]
The link above works for you? I does not for me!

**Comment by manojVivek** [comment]
Fixed this issue in v1.9.0. Please update the extensions and try again.
